# AAD Configuration File
# Controls artifact generation and API trigger behavior.

#The amount of time between api calls
api_frequency_seconds: 15

#The max amount of messages stored
cache_max_items: 100
cache_max_age_seconds: 30

# The LLM info used to select the model in llm_client.py
# Args:
#   model_provider: Name of model provider 
#   model: Name of specific model
llm: 
  model_provider: "openai"
  model: 'gpt-4o'

## TODO replace logic with ROSy way in sprint 3
trigger_script: False

raw_input_topic: "/ai_anomaly_logging"
alert_topic: "/aad/alerts"

throttle_info: true
info_min_period_sec: 0.1

log_every_n_msgs: 1
